name: Continuous Deployment (Prod)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push school image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rudrasankha/todo-app-week-39c3:${{ github.sha }}
          
      - name: Clone staging-ops repo, update image tags, and push tags
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Rudra-Sankha-Sinhamahapatra/argocd-gitops-deployment.git
          cd argocd-gitops-deployment
          
          echo "Current content of manifest.yaml:"
          cat manifest.yaml
          
          # Try a more specific sed pattern
          sed -i "s|image: rudrasankha/todo-app-week-39c3:[a-zA-Z0-9]*|image: rudrasankha/todo-app-week-39c3:${{ github.sha }}|" manifest.yaml
          
          echo "Content after sed command:"
          cat manifest.yaml
          
          # Show git status
          echo "Git status:"
          git status
          
          # Show if there are any changes
          echo "Git diff:"
          git diff
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add manifest.yaml
          git commit -m "Update school server image tags to ${{ github.sha }}"
          git push https://${PAT}@github.com/Rudra-Sankha-Sinhamahapatra/argocd-gitops-deployment.git main